### ISSUE TITLE
Auto Transfer feature

### ISSUE THREAD

**Issue by novaswandika** [PokeBotPub/PokeBot-Android#42]
Great app ! But I have a problem . The duplicate pokemon are always transferred when I 've turned off auto transfer pokemon on the settings. thanks .

**Comment by localhost127001** [comment]
Bump for fix
I got eevee with 100% IV but low CP and it got transfered!
Already turn off auto transfer and remove all filter lists, even as far make it as favorites in-game just in case but still

**Comment by macinmn** [comment]
Same issue.  Already had turned off auto-transfer and have tried setting keep max duplicates but everything but 1 keeps getting transfered.  All except Snorlax (including some nice Vaporeon, Flareon, Exeggutor, Lapras) because Snorlax is on exception list.  I really don't want to create exception for all, since you need to scroll manually, can't type in, which makes it a lot of work to add Dragonite, Dragonair, etc.  I just want to transfer manually and want feature off, when I turn it off.  
Thanks for the nice app though.

**Comment by PokeBotPub** [comment]
Sorry guys, just i forget one line check function. I was fixed, its come with new patch.

**Comment by ericlay925** [comment]
Today, when I login to pokebot 1.0.12, the app shows the new version is 1.1. However, I can not download it from app automatically. Where can I download new version 1.1 from this site? thanks.

**Comment by macinmn** [comment]
issue still exists in 1.0.13

set to '20' value and it immediately transferred my 2nd best Dratini.  I immediately disengaged bot.  I have no filter set for Dratini or other species.
